all:
	(cd LuaAlchemyDemo; ant)
	(cd MiniDemo; ant)
	(cd Rapid; ant)
	(cd NoAssets; ant)
	(cd Barebones; make)
	(cd EzPlatformer; ant)
# Note: This is excluded as it requires certificates and stuff
#       to be configured on developers's machine.
#       Read the Adobe docs to figure out how to do that.
# 	(cd MiniDemoAIR; ant clear)

clean:
	(cd LuaAlchemyDemo; ant clear)
	(cd MiniDemo; ant clear)
	(cd Rapid; ant clear)
	(cd NoAssets; ant clear)
	(cd Barebones; make clean)
	(cd EzPlatformer; ant clear)
	(cd MiniDemoAIR; ant clear)
