all:
	(cd LuaAlchemyDemo; ant)
	(cd MiniDemo; ant)
	(cd Rapid; ant)
	(cd NoAssets; ant)
	(cd Barebones; make)

clean:
	(cd LuaAlchemyDemo; ant clear)
	(cd MiniDemo; ant clear)
	(cd Rapid; ant clear)
	(cd NoAssets; ant clear)
	(cd Barebones; make clean)
