-- tserialize-autogen.lua: autogenerated random tests for tserialize
-- This file is a part of lua-nucleo library
-- Copyright (c) lua-nucleo authors (see file `COPYRIGHT` for the license)

dofile('lua-nucleo/strict.lua')
dofile('lua-nucleo/import.lua')

local make_suite = select(1, ...)
assert(type(make_suite) == "function")

local check_ok  = import 'test/lib/tserialize-test-utils.lua' { 'check_ok' }
local gen_random_dataset = import 'test/lib/table.lua' { 'gen_random_dataset' }

local test = make_suite("Autogenerated tests")

for i = 1, 500 do
  test (string.format("Random autogen test#%d",i)) (function()
    check_ok(gen_random_dataset())
  end)
end

assert(test:run())
