#!/bin/bash

if git-rev-parse --verify HEAD 2>/dev/null
then
        against=HEAD
else
        # Initial commit: diff against an empty tree object
        against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

git diff-index --check --cached $against -- || exit 1

# check lua syntax
for i in `git diff-index --cached HEAD | egrep "\\.lua$" | cut -d " " -f 4`; do
  git show $i | luac -p - || exit 1
done
